version: '3.7'
services:
  prefect-agent:
    container_name: prefect-agent-microstrategy
    command: ["/root/agent/start_agent.sh"]
    build: .
    restart: always
    volumes:
      - /tmp:/tmp
      - ./prefect_bootstrap:/root/agent
      - ./make_kv_store.py:/root/make_kv_store.py
      - ./mstro_to_s3/:/root/mstro_to_s3
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./prefect_agent_environment_variables.env
