# This is a basic workflow to help you get started with Actions

name: Register Flows

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - production
    paths:
      - ".github/workflows/prefect_helper.sh"
      - ".github/workflows/register_flows.yml"
      - "flows/**"
  pull_request:
    paths:
      - ".github/workflows/prefect_helper.sh"
      - ".github/workflows/register_flows.yml"
      - "flows/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      description:
        default: ""

#
# Jobs
#
jobs:
  register_flows:
    name: Register Flows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      # Get the code first
      - name: "Checkout"
        uses: actions/checkout@v2
      # Then install the AWC CLI tools & boto3
      - name: "Installing Prefect"
        run: |
          sudo apt-get install -y python3-setuptools
          pip3 install awscli boto3 virtualenv requests
      # Run the shell commands using the AWS environment variables
      - name: "Register Flows"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PREFECT_KEY: ${{ secrets.PREFECT_KEY }}
          PREFECT_PRNUM: ${{ github.event.pull_request.number }}
          PREFECT_PRBODY: ${{ github.event.pull_request.body }}
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          echo "Prefect Dispatch @ ${BRANCH_NAME}: ${{ github.event.inputs.description }}"
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTION/BRANCH_NAME: ${BRANCH_NAME}"
          echo "PREFECT_PRNUM: ${PREFECT_PRNUM}"
          echo "PWD: $(pwd)"
          docker pull atddocker/atd-prefect-builder:latest
          source $(pwd)/.github/workflows/prefect_helper.sh
          register_tasks
